[[plugins]]
repo = 'Shougo/dein.vim'
# [[plugins]]
# repo = 'scrooloose/nerdtree'
# [[plugins]]
# repo = 'tpope/vim-fugitive'
# hook_add = '''
    # nnoremap [figitive] <Nop>
    # nnoremap <Leader>g [figitive]
    # nnoremap <silent> [figitive]s :<C-u>Gstatus<CR>
    # nnoremap <silent> [figitive]d :<C-u>Gdiff<CR>
    # nnoremap <silent> [figitive]b :<C-u>Gblame<CR>
# '''
# [[plugins]]
# repo = 'Xuyuanp/nerdtree-git-plugin'
# depends =  ['vim-fugitive']
[[plugins]]
repo = 'airblade/vim-gitgutter'
[[plugins]]
repo = 'c9s/cascading.vim'
[[plugins]]
repo = 'scrooloose/nerdcommenter.git'
[[plugins]]
repo = 'godlygeek/tabular'
[[plugins]]
repo = 'vim-scripts/camelcasemotion'
[[plugins]]
repo = 'easymotion/vim-easymotion'
[[plugins]]
repo = 'yegappan/grep'
[[plugins]]
repo = 'othree/eregex.vim'
[[plugins]]
repo = 'thinca/vim-quickrun'
[[plugins]]
repo = 'thinca/vim-ref'
[[plugins]]
repo = 'vim-scripts/errormarker.vim'
[[plugins]]
repo = 'scrooloose/syntastic'
[[plugins]]
repo = 'w0rp/ale'
[[plugins]]
repo = 'fholgado/minibufexpl.vim'
[[plugins]]
repo = 'vim-scripts/taglist.vim'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'
[[plugins]]
repo = 'itchyny/lightline.vim'
[[plugins]]
repo = 'airblade/vim-gitgutter'
[[plugins]]
repo = 'majutsushi/tagbar'
[[plugins]]
repo = 'osyo-manga/vim-over'
[[plugins]]
repo = 'LeafCage/yankround.vim'
[[plugins]]
repo = 'tyru/open-browser.vim'
[[plugins]]
repo = 'w0ng/vim-hybrid'
[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
let g:airline_powerline_fonts = 1
'''
[[plugins]]
repo = 'vim-airline/vim-airline-themes'
[[plugins]]
repo = 'yuroyoro/yuroyoro256.vim'
[[plugins]]
repo = 'joshdick/onedark.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

[[plugins]]
repo = 'xwsoul/vim-zephir'
[[plugins]]
repo = 'osyo-manga/shabadou.vim'
